
spring:


  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
    username: postgres.prfskcdzokiaforiyaar
    password: cns20240!@#
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1
      embedding:
        options:
          model: text-embedding-3-small

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.web: DEBUG
#huggingface:
#  api-key: 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
#  embedding-model: BAAI/bge-small-en

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: ${PORT:8080}
